#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.5 on Tue Aug  7 19:34:16 2007 from /home/kepler/workspace/E-Dictor/src/e-dictor.wxg

import wx, __builtin__
import encodings.utf_8, os, sys
import lxml._elementpath

from MainFrame import MainFrame

class EDictor(wx.App):
    def OnInit(self):
        wx.InitAllImageHandlers()
        frame_main = MainFrame(None, -1, "")
        self.SetTopWindow(frame_main)
        frame_main.Show()
        return 1

# end of class EDictor

'''
Version control:

        9.9.[a/b]999
        | | |     |__> Release number
        | | |____> Alpha or Beta
        | |______> Major changes to code (revision/fix/improvement/interface)
        |________> Code/Interface completely rebuilt

The decision about major/minor is up the developers. For candidate
versions (if needed) it should be used 'rc' + number. E.g.:

        1.0rc1
'''
class Version():
    def __str__(self):
        return "1.0.b008"

__version__ = Version()
__builtin__.version = __version__

if __name__ == "__main__":
    edictor = EDictor(0)
    edictor.MainLoop()
    #cProfile.run(edictor.MainLoop())
