# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Mon May 25 14:09:24 2009

import wx, MainFrame

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade

class EditionReplaceDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: EditionReplaceDialog.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.label_23 = wx.StaticText(self, -1, _(u"Confirma a aplicação da edição sobre esta ocorrência?"))
        self.btn_replace_all = wx.Button(self, -1, _("Substituir &todas"))
        self.btn_replace = wx.Button(self, -1, _("&Substituir"))
        self.btn_skip = wx.Button(self, -1, _("&Ignorar"))
        self.btn_close = wx.Button(self, -1, _("&Fechar"))

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.OnReplaceAllButtonClick, self.btn_replace_all)
        self.Bind(wx.EVT_BUTTON, self.OnReplaceButtonClick, self.btn_replace)
        self.Bind(wx.EVT_BUTTON, self.OnIgnoreButtonClick, self.btn_skip)
        self.Bind(wx.EVT_BUTTON, self.OnCancelButtonClick, self.btn_close)
        # end wxGlade

        self.Bind(wx.EVT_SHOW, self.OnShow)
        self.Bind(wx.EVT_CLOSE, self.OnClose)
        self.Bind(wx.EVT_CHAR_HOOK, self.OnKeyDown)

        self.main_window_ref = None

    def __set_properties(self):
        # begin wxGlade: EditionReplaceDialog.__set_properties
        self.SetTitle(_("Substituir similares"))
        self.btn_replace.SetFocus()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: EditionReplaceDialog.__do_layout
        sizer_33 = wx.BoxSizer(wx.VERTICAL)
        sizer_59 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_33.Add(self.label_23, 0, wx.TOP|wx.BOTTOM|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 20)
        sizer_59.Add(self.btn_replace_all, 0, 0, 0)
        sizer_59.Add(self.btn_replace, 0, wx.LEFT|wx.RIGHT, 15)
        sizer_59.Add(self.btn_skip, 0, wx.RIGHT, 15)
        sizer_59.Add(self.btn_close, 0, 0, 0)
        sizer_33.Add(sizer_59, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5)
        self.SetSizer(sizer_33)
        sizer_33.Fit(self)
        self.Layout()
        # end wxGlade

    def OnClose(self, event):
        """
        Handles the user clicking the window/dialog "close" button/icon.
        """
        event.Skip()

    def OnKeyDown(self, event):
        keycode = event.GetKeyCode()
        if keycode == wx.WXK_ESCAPE:
            self.Close(True)
        event.Skip()

    def configureDialog(self, main_window):
        '''
        Configure dialog based on main_window state.
        '''
        # Change the position of the dialog, to avoid hiding the selected word
        self.main_window_ref = main_window

    def OnShow(self, event):
        ''' desativado
        if self.main_window_ref.notebook_1.GetCurrentPage().GetId() == MainFrame.ID_TAB_MOR:
            pos_y = (self.main_window_ref.morpho_cell.GetAbsPos().y + self.main_window_ref.morpho_text_html_window.GetScreenPosition().y + 50)
        else:
            pos_y = (self.main_window_ref.graphy_cell.GetAbsPos().y + self.main_window_ref.graphy_text_html_window.GetScreenPosition().y + 50)
        if pos_y < (self.main_window_ref.GetSizeTuple()[1] - self.GetSizeTuple()[1]):
            self.MoveXY(self.main_window_ref.GetSizeTuple()[0] - self.GetSizeTuple()[0],
                        self.main_window_ref.GetSizeTuple()[1] - self.GetSizeTuple()[1])
        else:
            self.MoveXY(self.main_window_ref.GetSizeTuple()[0] - self.GetSizeTuple()[0],
                        pos_y - (self.GetSizeTuple()[1] + 100))
        '''

    def OnReplaceAllButtonClick(self, event): # wxGlade: EditionReplaceDialog.<event_handler>
        # Close window
        self.EndModal(wx.ID_REPLACE_ALL)

    def OnReplaceButtonClick(self, event): # wxGlade: EditionReplaceDialog.<event_handler>
        # Close window
        self.EndModal(wx.ID_REPLACE)

    def OnCancelButtonClick(self, event): # wxGlade: EditionReplaceDialog.<event_handler>
        # Close window
        self.EndModal(wx.ID_CANCEL)

    def OnIgnoreButtonClick(self, event): # wxGlade: EditionReplaceDialog.<event_handler>
        # Close window
        self.EndModal(wx.ID_IGNORE)

# end of class EditionReplaceDialog


