# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Wed Sep 28 17:37:44 2011

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade

class ExportTagsDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: ExportTagsDialog.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.sizer_78_copy_staticbox = wx.StaticBox(self, -1, _(u"Opções"))
        self.lbl_nivel_ed = wx.StaticText(self, -1, _(u"Nível de edição:"))
        self.cbo_nivel_ed = wx.ComboBox(self, -1, choices=[], style=wx.CB_DROPDOWN|wx.CB_READONLY)
        self.chk_ids = wx.CheckBox(self, -1, _(u"Imprimir IDs para sentenças"))
        self.chk_pages = wx.CheckBox(self, -1, _(u"Imprimir numeração de página"))
        self.button_ok = wx.Button(self, -1, _("Ok"))
        self.button_cancel = wx.Button(self, -1, _("Cancelar"))

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.OnOkButtonClick, self.button_ok)
        self.Bind(wx.EVT_BUTTON, self.OnCancelButtonClick, self.button_cancel)
        # end wxGlade

        self.Bind(wx.EVT_CHAR_HOOK, self.OnKeyDown)
        
        self.options = []

    def OnKeyDown(self, event):
        keycode = event.GetKeyCode()
        if keycode == wx.WXK_ESCAPE:
            self.Close(True)
        event.Skip()

    def __set_properties(self):
        # begin wxGlade: ExportTagsDialog.__set_properties
        self.SetTitle(_(u"Exportar sentenças etiquetadas"))
        self.lbl_nivel_ed.SetMinSize((122, 14))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: ExportTagsDialog.__do_layout
        sizer_74_copy = wx.BoxSizer(wx.VERTICAL)
        sizer_2_copy_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_78_copy = wx.StaticBoxSizer(self.sizer_78_copy_staticbox, wx.VERTICAL)
        sizer_76_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_76_copy.Add(self.lbl_nivel_ed, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 5)
        sizer_76_copy.Add(self.cbo_nivel_ed, 0, wx.ALL, 2)
        sizer_74_copy.Add(sizer_76_copy, 0, wx.EXPAND, 0)
        sizer_78_copy.Add(self.chk_ids, 0, 0, 0)
        sizer_78_copy.Add(self.chk_pages, 0, 0, 0)
        sizer_74_copy.Add(sizer_78_copy, 1, wx.EXPAND, 0)
        sizer_2_copy_2.Add(self.button_ok, 1, wx.LEFT|wx.RIGHT|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 30)
        sizer_2_copy_2.Add(self.button_cancel, 1, wx.LEFT|wx.RIGHT|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 30)
        sizer_74_copy.Add(sizer_2_copy_2, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL, 10)
        self.SetSizer(sizer_74_copy)
        sizer_74_copy.Fit(self)
        self.Layout()
        # end wxGlade

    def OnOkButtonClick(self, event): # wxGlade: ExportTagsDialog.<event_handler>
        if self.chk_ids.GetValue():
            self.options.append('IDs')
        if self.chk_pages.GetValue():
            self.options.append('PAGES')
        # Close window
        self.EndModal(wx.ID_OK)

    def OnCancelButtonClick(self, event): # wxGlade: ExportTagsDialog.<event_handler>
        self.options = []
        self.EndModal(wx.ID_CANCEL)

    def getEditionLevel(self):
        return self.cbo_nivel_ed.GetStringSelection()
    
    def getOptions(self):
        return self.options
    
    def setEditionLabels(self, ed_labels):
        self.cbo_nivel_ed.Clear()
        for ed in ed_labels:
            self.cbo_nivel_ed.Append(ed)
        self.cbo_nivel_ed.Select(0)
        self.cbo_nivel_ed.SetFocus()

# end of class ExportTagsDialog


