# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Wed Aug 26 17:46:53 2009

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade

class InsertPNDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: InsertPNDialog.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.label_31 = wx.StaticText(self, -1, _(u"Número da página:"))
        self.text_ctrl_4 = wx.TextCtrl(self, -1, "")
        self.radio_box_1 = wx.RadioBox(self, -1, _("Inserir no"), choices=[_(u"Cabeçalho"), _(u"Rodapé")], majorDimension=0, style=wx.RA_SPECIFY_ROWS)
        self.button_ok = wx.Button(self, -1, _("Ok"))
        self.button_cancel = wx.Button(self, -1, _("Cancelar"))

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.OnOkButtonClick, self.button_ok)
        self.Bind(wx.EVT_BUTTON, self.OnCancelButtonClick, self.button_cancel)
        # end wxGlade

        self.Bind(wx.EVT_CHAR_HOOK, self.OnKeyDown)
        self.text_ctrl_4.SetFocus()

    def __set_properties(self):
        # begin wxGlade: InsertPNDialog.__set_properties
        self.SetTitle(_(u"Edição"))
        self.radio_box_1.SetSelection(0)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: InsertPNDialog.__do_layout
        sizer_1_copy = wx.BoxSizer(wx.VERTICAL)
        sizer_2_copy_1 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_73 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_73.Add(self.label_31, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 5)
        sizer_73.Add(self.text_ctrl_4, 0, wx.TOP|wx.BOTTOM, 5)
        sizer_1_copy.Add(sizer_73, 0, wx.EXPAND, 0)
        sizer_3_copy.Add(self.radio_box_1, 2, 0, 0)
        sizer_1_copy.Add(sizer_3_copy, 1, wx.LEFT|wx.RIGHT|wx.EXPAND, 5)
        sizer_2_copy_1.Add(self.button_ok, 1, wx.LEFT|wx.RIGHT|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 10)
        sizer_2_copy_1.Add(self.button_cancel, 1, wx.LEFT|wx.RIGHT|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 10)
        sizer_1_copy.Add(sizer_2_copy_1, 0, wx.ALL|wx.EXPAND, 10)
        self.SetSizer(sizer_1_copy)
        sizer_1_copy.Fit(self)
        self.Layout()
        # end wxGlade

    def OnOkButtonClick(self, event): # wxGlade: InsertPNDialog.<event_handler>
        if self.text_ctrl_4.GetValue().strip() == '':
            wx.MessageBox(_(u'O número de página precisa ser informado!'), 'E-Dictor')
            return
        # Close window
        self.EndModal(wx.ID_OK)

    def OnCancelButtonClick(self, event): # wxGlade: InsertPNDialog.<event_handler>
        self.EndModal(wx.ID_CANCEL)

    def OnKeyDown(self, event):
        keycode = event.GetKeyCode()
        if keycode == wx.WXK_ESCAPE:
            self.Close(True)
        if keycode == 13:
            self.OnOkButtonClick(None)
        event.Skip()
        
    def getPagePos(self):
        return self.radio_box_1.GetSelection()
    
    def getPageNumber(self):
        return self.text_ctrl_4.GetValue().strip()

# end of class InsertPNDialog


