# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Fri Jan  9 17:23:51 2009

import wx, intl

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade

class InsertBreakDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # Set app language
        intl.setLanguage()
        # begin wxGlade: InsertBreakDialog.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.sizer_5_staticbox = wx.StaticBox(self, -1, _(u"Opções"))
        self.label_10 = wx.StaticText(self, -1, _("Posicione o sinal \"|\" para indicar o local da quebra:"))
        self.text_ctrl_1 = wx.TextCtrl(self, -1, "")
        self.radio_box_1 = wx.RadioBox(self, -1, _("Tipo de quebra"), choices=[_("Linha"), _("Coluna"), _(u"Página")], majorDimension=0, style=wx.RA_SPECIFY_ROWS)
        self.checkbox_3 = wx.CheckBox(self, -1, _(u"Número da linha"))
        self.text_ctrl_2 = wx.TextCtrl(self, -1, "")
        self.button_ok = wx.Button(self, -1, _("Ok"))
        self.button_cancel = wx.Button(self, -1, _("Cancelar"))

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_TEXT_ENTER, self.OnOkButtonClick, self.text_ctrl_1)
        self.Bind(wx.EVT_RADIOBOX, self.OnBreakTypeClick, self.radio_box_1)
        self.Bind(wx.EVT_CHECKBOX, self.OnLineNumberClick, self.checkbox_3)
        self.Bind(wx.EVT_BUTTON, self.OnOkButtonClick, self.button_ok)
        self.Bind(wx.EVT_BUTTON, self.OnCancelButtonClick, self.button_cancel)
        # end wxGlade

        self.break_type = ''
        self.options = []
        self.original_word = ''

        self.text_ctrl_1.SetFocus()
        self.Bind(wx.EVT_CHAR_HOOK, self.OnKeyDown)

    def OnKeyDown(self, event):
        keycode = event.GetKeyCode()
        if keycode == wx.WXK_ESCAPE:
            self.Close(True)
        elif keycode == 13:
            self.OnOkButtonClick(event)
        event.Skip()

    def __set_properties(self):
        # begin wxGlade: InsertBreakDialog.__set_properties
        self.SetTitle(_("Inserir quebra"))
        self.SetSize((345, 194))
        self.radio_box_1.SetSelection(0)
        # end wxGlade

        self.text_ctrl_2.Enable(False)

    def __do_layout(self):
        # begin wxGlade: InsertBreakDialog.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5 = wx.StaticBoxSizer(self.sizer_5_staticbox, wx.HORIZONTAL)
        sizer_6 = wx.BoxSizer(wx.VERTICAL)
        sizer_7 = wx.BoxSizer(wx.VERTICAL)
        sizer_7.Add(self.label_10, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_7.Add(self.text_ctrl_1, 0, wx.ALL|wx.EXPAND, 5)
        sizer_1.Add(sizer_7, 0, wx.ALL|wx.EXPAND, 5)
        sizer_3.Add(self.radio_box_1, 2, 0, 0)
        sizer_6.Add(self.checkbox_3, 0, wx.EXPAND, 10)
        sizer_6.Add(self.text_ctrl_2, 0, 0, 0)
        sizer_5.Add(sizer_6, 1, wx.EXPAND, 0)
        sizer_3.Add(sizer_5, 3, wx.LEFT|wx.EXPAND, 10)
        sizer_1.Add(sizer_3, 1, wx.LEFT|wx.RIGHT|wx.EXPAND, 5)
        sizer_2.Add(self.button_ok, 1, wx.LEFT|wx.RIGHT|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 30)
        sizer_2.Add(self.button_cancel, 1, wx.LEFT|wx.RIGHT|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 30)
        sizer_1.Add(sizer_2, 0, wx.ALL|wx.EXPAND, 10)
        self.SetSizer(sizer_1)
        self.Layout()
        self.Centre()
        # end wxGlade

    def OnBreakTypeClick(self, event): # wxGlade: InsertBreakDialog.<event_handler>
        if self.radio_box_1.GetSelection() == 0:
            self.checkbox_3.Enable(True)
            self.text_ctrl_2.Enable(True)
        if self.radio_box_1.GetSelection() == 1:
            self.checkbox_3.Enable(False)
            self.checkbox_3.SetValue(False)
            self.text_ctrl_2.Enable(False)
            self.text_ctrl_2.ChangeValue('')
        if self.radio_box_1.GetSelection() == 2:
            self.checkbox_3.Enable(False)
            self.checkbox_3.SetValue(False)
            self.text_ctrl_2.Enable(False)
            self.text_ctrl_2.ChangeValue('')

    def OnOkButtonClick(self, event): # wxGlade: InsertBreakDialog.<event_handler>
        if self.text_ctrl_1.GetValue().find('|>') > -1:
            wx.MessageBox(_(u"Quebras não podem ser adjacentes."), "E-Dictor", wx.ID_OK)
            self.text_ctrl_1.ChangeValue(self.original_word)
            return
        if self.text_ctrl_1.GetValue().find('|') < 0:
            wx.MessageBox(_(u"É preciso marcar a posição da quebra na palavra, com o sinal '|'."), "E-Dictor", wx.ID_OK)
            self.text_ctrl_1.ChangeValue(self.original_word)
            return
        if self.text_ctrl_1.GetValue().replace('|','') != self.original_word.replace('|',''):
            wx.MessageBox(_(u"A forma original da palavra não deve ser modificada."), "E-Dictor", wx.ID_OK).ShowModal()
            self.text_ctrl_1.ChangeValue(self.original_word)
            return
        t_list = ['l','c','p']
        self.break_type = t_list[self.radio_box_1.GetSelection()]
        if self.checkbox_3.GetValue():
            self.options.append('ln')
        # Close window
        self.EndModal(wx.ID_OK)

    def OnCancelButtonClick(self, event): # wxGlade: InsertBreakDialog.<event_handler>
        self.EndModal(wx.ID_CANCEL)
        
    def setBreakString(self, str):
        self.original_word = str
        self.text_ctrl_1.ChangeValue(str)
    
    def getBreakString(self):
        return self.text_ctrl_1.GetValue()
    
    def getBreakType(self):
        return self.break_type
    
    def getOptions(self):
        return self.options
    
    def getLineNr(self):
        return self.text_ctrl_2.GetValue()

    def OnLineNumberClick(self, event): # wxGlade: InsertBreakDialog.<event_handler>
        self.text_ctrl_2.Enable(self.checkbox_3.GetValue())
        if self.checkbox_3.GetValue():
            self.text_ctrl_2.SetFocus()

# end of class InsertBreakDialog


